### PR TITLE
Reject promise in case of GraphQL errors. Closes #2

### LINKED ISSUE #2: Handle GraphQL errors
Hello, 

First of all, thanks for this simple but very useful lib. I started using it but I noticed that it wasn't showing me about some GraphQL errors I had, for example when not implementing mocks for custom scalars.

So I copied and pasted your implementation in my own project and changed it to the following:

```javascript
require("babel-polyfill");

const {
  makeExecutableSchema,
  addMockFunctionsToSchema
} = require("graphql-tools");
const {
  graphql,
  printSchema,
  buildClientSchema,
  GraphQLScalarType
} = require("graphql");

function getNetworkLayer({ schema, mocks, resolvers }) {
  return async function fetchQuery(operation, variableValues) {
    if (typeof schema === "object" && schema.data) {
      schema = printSchema(buildClientSchema(schema.data));
    }

    const executableSchema = makeExecutableSchema({
      typeDefs: schema,
      resolvers
    });

    // Add mocks, modifies schema in place
    addMockFunctionsToSchema({
      schema: executableSchema,
      mocks,
      preserveResolvers: false
    });

    const result = await graphql(
      executableSchema,
      operation.text,
      null,
      null,
      variableValues
    );

    if (result.errors && result.errors.length > 0) {
      return Promise.reject(result);
    }

    return Promise.resolve(result);
  };
}
```

With that, you can get those mentioned errors in the QueryRenderer. As you can see, it uses `async/await`. I wanted send you a pull request but I didn't know how to handle the `babel-polyfill` dependency. Do you think we can include it as a `peerDependency` or we have to avoid using `async/await`?

### PR DESCRIPTION
**Pull request by hisapy**
The following screenshot shows the kind of errors you can catch with the modifications in this PR

screen shot 2018-01-17 at 8 41 32 am

### CODE REVIEW

**Comment by robrichard** [comment]
@hisapy Thanks for the PR, I think this change is good. Can you update to preserve the original code style (4 space tabs, 100 character line widths) and minimize whitespace changes?

**Comment by hisapy** [comment]
Sure. The formatting was caused by my _prettier_. I'll update it ASAP

**Comment by hisapy** [comment]
Hey @robrichard . I hope I fixed the format. Please take a look at it. 

I have installed it from my fork and it is still working `yarn add -D https://github.com/iporaitech/relay-mock-network-layer`. 😅 

Mocking the network layer is really a powerful thing. It takes Relay+Storyshots to another level. One really cool thing is that the mocking mechanism _auto populates the responses with data_ with "Hello World", when you don't provide mocks for it and when the fields doesn't contain custom scalars.

relay-mock-network-layer_automocking


The above .gif was taken from my Storybook. I'll try to write a blog post about this ASAP.

**Comment by robrichard** [comment]
Thanks @hisapy! I published `relay-mock-network-layer@1.2.0` with your change.

**Pull request merged**
